#!/bin/bash

# ========================================
# PostgreSQL Backup Script for: {{APP_NAME}}
# Generated by postgres-backup-automation
# ========================================

# App-specific configuration
APP_NAME="{{APP_NAME}}"
VOLUME_PATH="/mnt/HC_Volume_{{VOLUME_ID}}"
DOCKER_CONTAINER="{{CONTAINER_NAME}}"
DB_USER="{{DB_USER}}"
DB_NAME="{{DB_NAME}}"

# S3 Configuration
S3_BUCKET="{{S3_BUCKET}}"
S3_PREFIX="{{APP_NAME}}/postgres-backups"
AWS_REGION="{{AWS_REGION}}"

# Backup settings
BACKUP_DIR="$VOLUME_PATH/backups"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
RETENTION_DAYS={{RETENTION_DAYS}}
STORAGE_CLASS="{{STORAGE_CLASS}}"

# ========================================
# Backup Process
# ========================================

# Ensure backup directory exists
mkdir -p $BACKUP_DIR

echo "[$APP_NAME] [$(date)] Starting backup..."

# Step 1: Create local backup
docker exec $DOCKER_CONTAINER pg_dump -U $DB_USER $DB_NAME | gzip > $BACKUP_DIR/backup_$TIMESTAMP.sql.gz

if [ $? -ne 0 ]; then
    echo "[$APP_NAME] [$(date)] ❌ Local backup FAILED!"
    exit 1
fi

# Get backup size
BACKUP_SIZE=$(du -h $BACKUP_DIR/backup_$TIMESTAMP.sql.gz | cut -f1)
echo "[$APP_NAME] [$(date)] ✅ Local backup completed: backup_$TIMESTAMP.sql.gz ($BACKUP_SIZE)"

# Create "latest" symlink
ln -sf $BACKUP_DIR/backup_$TIMESTAMP.sql.gz $BACKUP_DIR/latest.sql.gz

# Step 2: Sync to S3
echo "[$APP_NAME] [$(date)] Syncing to S3..."
aws s3 cp $BACKUP_DIR/backup_$TIMESTAMP.sql.gz \
    s3://$S3_BUCKET/$S3_PREFIX/backup_$TIMESTAMP.sql.gz \
    --region $AWS_REGION \
    --storage-class $STORAGE_CLASS

if [ $? -eq 0 ]; then
    echo "[$APP_NAME] [$(date)] ✅ S3 sync completed successfully"
    
    # Verify upload
    aws s3 ls s3://$S3_BUCKET/$S3_PREFIX/backup_$TIMESTAMP.sql.gz --region $AWS_REGION > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        echo "[$APP_NAME] [$(date)] ✅ Backup verified in S3"
    else
        echo "[$APP_NAME] [$(date)] ⚠️  WARNING: Could not verify S3 backup!"
    fi
else
    echo "[$APP_NAME] [$(date)] ⚠️  S3 sync FAILED (local backup still available)"
    # Don't exit - local backup is still good
fi

# Step 3: Cleanup old local backups
DELETED=$(find $BACKUP_DIR -name "backup_*.sql.gz" -mtime +$RETENTION_DAYS -delete -print | wc -l)
echo "[$APP_NAME] [$(date)] 🗑️  Deleted $DELETED old local backup(s)"

# Step 4: Summary
LOCAL_COUNT=$(find $BACKUP_DIR -name "backup_*.sql.gz" | wc -l)
echo "[$APP_NAME] [$(date)] ========================================="
echo "[$APP_NAME] [$(date)] Backup Summary:"
echo "[$APP_NAME] [$(date)]   - Latest: backup_$TIMESTAMP.sql.gz ($BACKUP_SIZE)"
echo "[$APP_NAME] [$(date)]   - Local: $LOCAL_COUNT files"
echo "[$APP_NAME] [$(date)]   - S3: s3://$S3_BUCKET/$S3_PREFIX/"
echo "[$APP_NAME] [$(date)] ========================================="
echo "[$APP_NAME] [$(date)] ✅ Backup complete!"
