#!/bin/bash

# ========================================
# Multi-App PostgreSQL Backup Health Check
# Generated by postgres-backup-automation
# ========================================

MAX_AGE_HOURS={{MAX_BACKUP_AGE_HOURS}}
OVERALL_STATUS="OK"

echo "========================================="
echo "PostgreSQL Backup Health Check"
echo "Date: $(date)"
echo "========================================="
echo ""

{{APPS_CHECK_BLOCK}}

echo "========================================="
if [ "$OVERALL_STATUS" == "OK" ]; then
    echo "Overall Status: ✅ HEALTHY"
    exit 0
elif [ "$OVERALL_STATUS" == "WARNING" ]; then
    echo "Overall Status: ⚠️  WARNING"
    exit 2
else
    echo "Overall Status: ❌ FAILED"
    exit 1
fi
