#!/bin/bash

# ========================================
# PostgreSQL Restore Script for: {{APP_NAME}}
# Generated by postgres-backup-automation
# ========================================

if [ -z "$1" ]; then
    echo "Usage: $0 <backup_file.sql.gz>"
    echo ""
    echo "Examples:"
    echo "  # Restore from local backup:"
    echo "  $0 /mnt/HC_Volume_{{VOLUME_ID}}/backups/latest.sql.gz"
    echo "  $0 /mnt/HC_Volume_{{VOLUME_ID}}/backups/backup_20260314_020000.sql.gz"
    echo ""
    echo "  # Restore from S3:"
    echo "  $0 s3://{{S3_BUCKET}}/{{APP_NAME}}/postgres-backups/backup_20260314_020000.sql.gz"
    exit 1
fi

APP_NAME="{{APP_NAME}}"
BACKUP_FILE=$1
DB_NAME="{{DB_NAME}}"
DB_USER="{{DB_USER}}"
DOCKER_CONTAINER="{{CONTAINER_NAME}}"
TEMP_FILE="/tmp/restore_${APP_NAME}_$$.sql.gz"
AWS_REGION="{{AWS_REGION}}"

# If S3 path, download first
if [[ $BACKUP_FILE == s3://* ]]; then
    echo "[$APP_NAME] Downloading from S3..."
    aws s3 cp $BACKUP_FILE $TEMP_FILE --region $AWS_REGION
    if [ $? -ne 0 ]; then
        echo "[$APP_NAME] ❌ Failed to download from S3!"
        exit 1
    fi
    BACKUP_FILE=$TEMP_FILE
fi

# Verify file exists
if [ ! -f "$BACKUP_FILE" ]; then
    echo "[$APP_NAME] ❌ Backup file not found: $BACKUP_FILE"
    exit 1
fi

# Get backup size
BACKUP_SIZE=$(du -h $BACKUP_FILE | cut -f1)

echo "[$APP_NAME] ========================================="
echo "[$APP_NAME] PostgreSQL Restore"
echo "[$APP_NAME] ========================================="
echo "[$APP_NAME] Database: $DB_NAME"
echo "[$APP_NAME] Container: $DOCKER_CONTAINER"
echo "[$APP_NAME] Backup: $(basename $BACKUP_FILE) ($BACKUP_SIZE)"
echo "[$APP_NAME] ========================================="
echo ""
read -p "⚠️  This will OVERWRITE the database. Continue? (yes/no): " confirm

if [ "$confirm" != "yes" ]; then
    echo "[$APP_NAME] Restore cancelled."
    [ -f "$TEMP_FILE" ] && rm -f $TEMP_FILE
    exit 0
fi

# Drop active connections
echo "[$APP_NAME] Dropping active connections..."
docker exec $DOCKER_CONTAINER psql -U $DB_USER postgres -c \
    "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='$DB_NAME' AND pid <> pg_backend_pid();" 2>/dev/null

# Drop and recreate database
echo "[$APP_NAME] Recreating database..."
docker exec $DOCKER_CONTAINER psql -U $DB_USER postgres -c "DROP DATABASE IF EXISTS $DB_NAME;"
if [ $? -ne 0 ]; then
    echo "[$APP_NAME] ❌ Failed to drop database!"
    [ -f "$TEMP_FILE" ] && rm -f $TEMP_FILE
    exit 1
fi

docker exec $DOCKER_CONTAINER psql -U $DB_USER postgres -c "CREATE DATABASE $DB_NAME OWNER $DB_USER;"
if [ $? -ne 0 ]; then
    echo "[$APP_NAME] ❌ Failed to create database!"
    [ -f "$TEMP_FILE" ] && rm -f $TEMP_FILE
    exit 1
fi

# Restore backup
echo "[$APP_NAME] Restoring data..."
gunzip -c $BACKUP_FILE | docker exec -i $DOCKER_CONTAINER psql -U $DB_USER $DB_NAME

if [ $? -eq 0 ]; then
    echo "[$APP_NAME] ✅ Restore completed successfully!"
    
    # Recreate common extensions
    echo "[$APP_NAME] Recreating extensions..."
    docker exec $DOCKER_CONTAINER psql -U $DB_USER $DB_NAME -c "CREATE EXTENSION IF NOT EXISTS vector;" 2>/dev/null
    docker exec $DOCKER_CONTAINER psql -U $DB_USER $DB_NAME -c "CREATE EXTENSION IF NOT EXISTS pg_stat_statements;" 2>/dev/null
    
    echo "[$APP_NAME] ✅ All done!"
else
    echo "[$APP_NAME] ❌ Restore FAILED!"
    [ -f "$TEMP_FILE" ] && rm -f $TEMP_FILE
    exit 1
fi

# Cleanup temp file
[ -f "$TEMP_FILE" ] && rm -f $TEMP_FILE
